# Generated by Django 2.0 on 2017-12-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sib_order', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('video', models.FileField(null=True, upload_to='')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='sky.MagicNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
