# Generated by Django 2.0 on 2017-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_auto_20171215_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
