# Generated by Django 2.0 on 2017-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0004_auto_20171215_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Figure'),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='friends',
            field=models.ManyToManyField(related_name='_magicnode_friends_+', to='sky.MagicNode'),
        ),
    ]
