# Generated by Django 2.0 on 2017-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0005_auto_20171216_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_magicnode_friends_+', to='sky.MagicNode'),
        ),
    ]
