# Generated by Django 2.0 on 2017-12-18 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0006_auto_20171216_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='sites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='magicnode',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_magicnode_friends_+', to='sky.MagicNode'),
        ),
    ]
