# Generated by Django 2.0 on 2017-12-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0007_auto_20171218_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicnode',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='magicnode',
            name='videos',
        ),
    ]
