# Generated by Django 2.0 on 2017-12-22 09:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sky', '0014_auto_20171218_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_like_the_topic', models.BooleanField()),
                ('i_like_the_content', models.BooleanField()),
                ('i_am_an_expert', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='magicnode',
            name='pre_nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='interest',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky.MagicNode'),
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
