# Generated by Django 2.0 on 2018-01-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0016_auto_20171231_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Рисунок'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='description',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Рисунок'),
        ),
        migrations.AlterField(
            model_name='newsrecord',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
    ]
