# Generated by Django 2.0 on 2018-01-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='node_last_visited',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sky.MagicNode'),
        ),
    ]
