# Generated by Django 2.0 on 2018-01-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0019_auto_20180127_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicnode',
            name='friends',
        ),
    ]
