# Generated by Django 2.0 on 2018-01-30 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0020_remove_magicnode_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=5),
        ),
    ]
