# Generated by Django 2.0 on 2018-02-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0021_magicnode_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicnode',
            name='video',
        ),
    ]
