# Generated by Django 2.0 on 2018-02-05 13:40

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0022_remove_magicnode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
