# Generated by Django 2.0 on 2018-02-05 14:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0023_magicnode_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicnode',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
