# Generated by Django 2.0 on 2018-02-08 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0025_magicnode_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='post_nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=5),
        ),
    ]
