# Generated by Django 2.0 on 2018-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0026_magicnode_post_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicnode',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magicnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
