# Generated by Django 2.0 on 2018-01-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sky', '0021_magicnode_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('n_sib', models.PositiveIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky.MagicNode')),
            ],
        ),
    ]
