# Generated by Django 2.0 on 2018-01-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['n_sib']},
        ),
    ]
