# Generated by Django 2.0 on 2018-01-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0017_auto_20180109_1020'),
        ('area', '0002_area_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaplus',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sky.MagicNode'),
            preserve_default=False,
        ),
    ]
